### ISSUE TITLE
Is Wikifundi using ZIM files?

### ISSUE THREAD

**Issue by sharun-s** [kelson42/wikifundi#5]
I am just trying to understand the difference between Kiwix and Wikifundi. With Kiwix I know I need a ZIM file and an executable for offline viewing. With Wikifundi can I reuse the ZIM files I have already downloaded to enable their offline editing?

**Comment by kelson42** [comment]
@sharun-s Kiwix is only about ready-only, so not editing. That said we have provided the system (kiwix-plug) and on the top of it we have integrated the Mediawiki engine which allow to train offline people to edit.

**Comment by kelson42** [comment]
I close the question as it seems to be answered.
